---
sidebar: sidebar 
permalink: nkfsfaq_netapp_service_engine_self-service_access_portal.html 
keywords: netapp, keystone, service, engine, self-service, acess, portal, 
summary: NetApp 服务引擎 / 自助服务访问门户 
---
= NetApp 服务引擎 / 自助服务访问门户
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下常见问题解答适用场景 NetApp 服务引擎。



=== 什么是 NetApp 服务引擎？

NetApp 服务引擎是一个自助服务门户，以 NetApp 运营的模式提供，您可以根据 NetApp Keystone Flex 订阅服务登录和配置存储。此外，该工具还可提供有关其订阅的消费水平的报告，并启动任何服务请求或订阅更改。



=== 客户运营模式是否需要 NetApp 服务引擎？

在客户操作的模式中，需要使用 NetApp 服务引擎。它提供有关消费详细信息的基本报告，并需要收集和报告计费信息。



=== NetApp 服务引擎安装在何处？

在 NetApp 运营的模式中， NetApp 服务引擎安装在 NetApp 提供的计算资源本地。在客户操作的模式下， NetApp 服务引擎安装在客户提供的计算资源上。



=== 谁可以登录到 NetApp 服务引擎？

用户可以根据 NetApp SSO 进行身份验证，也可以根据在 NetApp 服务引擎中配置的本地用户进行身份验证。



=== 如何控制访问？

NetApp 服务引擎提供基于角色的访问控制（ Role-Based Access Control ， RBAC ），并且每个用户都可以与某个角色关联，该角色定义了可执行的操作。RBAC 分配由客户使用 NetApp 服务引擎完成。



=== 可用的访问控制有哪些？

可以使用以下访问控制：

* * 合作伙伴管理员 * 合作伙伴一方的管理员，有权创建和管理租户，管理租户订阅，查看使用情况报告以及管理存储的技术方面。
* * 客户 / 租户管理员 * 客户端的管理人员，有权请求对订阅进行更改，创建新用户和子租户以及创建和查看文件共享，磁盘和分段。
* * NetApp 管理员（读取）。 * NetApp 管理员，有权访问 Web 门户的所有组件，并可查看所有详细信息，例如所有 NetApp Keystone 灵活订阅，合作伙伴和租户订阅以及存储。但是，此用户无权创建，编辑或删除。
* * NetApp 管理员 * 。此用户具有完全访问权限，可以在 NetApp 服务引擎 Web 门户中执行所有功能以管理 NetApp Keystone 灵活订阅，并执行所有活动以管理合作伙伴和租户。




=== 我可以从何处查看我的使用情况的计费？

您可以在信息板上的 * 每月费用 * 小工具中查看过去三个月订阅的总月费用。您可以通过单击小工具或导航到 * 管理 * > * 计费 * 来查看详细的计费信息。
