---
sidebar: sidebar 
permalink: nkfsosm_keystone_service_capacity_definitions.html 
keywords: netapp, keystone, service, capacity, definitions, burst, committed capacity, consumed capacity, billed capacity 
summary: Keystone 服务容量定义 
---
= Flex 订阅服务容量定义
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone 灵活订阅（ Flex 订阅）服务容量包括：



== 逻辑容量

这是客户放入 Flex 订阅基础架构的数据。所有 Flex 订阅容量均指逻辑容量。例如，如果一个 1 TiB 文件存储在 Flex 订阅基础架构上，则必须至少购买 1 TiB 的容量。



== 已提交容量

在期限内每月收取的最低逻辑容量：

* 容量用于每个性能级别。
* 在此期限内，不能减少已提交容量。
* 在此期限内，可以添加已提交的容量和额外的性能级别。




=== 已提交容量的更改

在订阅期限内，您可以更改已提交的容量。但是，存在某些前提条件：

* 已提交的容量不能减少
* 已提交容量不能在您的订阅到期前 90 天增加，除非此订阅将再续订 12 个月。
* 您可以通过 NetApp 服务引擎界面或 Keystone Success Manager 请求更改已提交容量。有关请求更改的信息，请参见 link:sewebiug_raise_a_service_request.html["提出服务请求"]。




== 突发容量

这是已超过已提交容量的逻辑容量。请注意以下几点：

* Flex 订阅服务提供的容量超过已承诺容量的 20% 。
* 突发容量可以灵活地使用，并按每日消耗的平均值进行收费。
* 突发容量的充电速率高达 20% ，与已承诺容量的充电速率相同。
* 超过已提交容量 20% 的突发容量按高级费率收费。如需了解超过 20% 的额外突发要求，请联系支持部门。




== 已用 / 已配置容量

已用容量是指服务当前使用的存储容量（以 TiB 为单位）。Flex 订阅服务会将特定性能服务级别上所有卷的已配置大小（而不是已用逻辑或物理容量）之和视为该性能服务级别的已用容量。其中包括：

* 通过卷的创建，修改，删除或潜在的自动增长配置的容量。
* Snapshot 副本和克隆。
+

NOTE: 不考虑在已配置容量内存储的数据量或实际写入磁盘的数据量。





== 计费容量

每月账单 = （已提交容量 [TiB] * 已提交速率 [$/TiB] ） + （每日平均已配置突发容量 [TiB] * 突发速率 [$/TiB] ）。每月账单包含基于已提交容量的最低费用。

根据每日平均突发容量消耗，每月费用可能会超过最低费用。有关计费的详细信息，请参见 link:nkfsosm_kfs_billing.html["Flex 订阅计费"]。
