---
sidebar: sidebar 
permalink: nkfsfaq_service_offer_details.html 
keywords: netapp, keystone, service, offer, details, 
summary: 服务优惠详细信息 
---
= Keystone服务产品
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下问题解答了您经常询问的有关NetApp Keystone Keystone服务产品的问题。

*最小已提交容量是多少？*

NetApp Keystone 订阅服务的最小已提交容量为每个站点在一个或多个服务层中的100 TiB。

* Keystone服务协议的典型期限是多长？*

Keystone服务提供12个月、24个月和36个月的期限。

如何访问存储？*

在 NetApp 操作的（标准）模式下，存储控制器（ ONTAP 系统管理器或对系统的管理访问）由 NetApp 拥有和管理。您只能通过 NetApp 服务引擎 UI 和 API 监控和管理存储。在客户管理的（或精简版）部署中， NetApp 服务引擎 UI 和 API 主要用于计费功能，您可以访问存储控制器，例如 Active IQ Unified Manager 和 ONTAP System Manager ，并直接访问 ONTAP 集群。

*如何管理此服务？*

NetApp 服务引擎是一款业务流程和管理工具，您可以使用它来配置存储并获取有关服务使用情况的报告。

*如何增加订阅中的已提交容量？*

您可以通过 NetApp 服务引擎管理工具或其 NetApp Keystone 成功经理提交容量添加请求。

*增加容量是否会延长此期限？*

所有增加的内容均为现有期限的共同期限，除非申请是在订阅后最后 90 天内提出的，在这种情况下，期限必须至少延长 12 个月。

*订阅能否同时进行？*

不可以、订阅条款彼此独立。

*是否可以向现有订阅添加备份存储？*

对于备份使用情形、您可以为现有或新服务级别的现有订阅添加容量、包括标准或价值服务级别。此操作不会更改现有订阅的期限。但有一个注意事项、即、如果您要在订阅期限的最后90天(即订阅结束前的最后90天)内添加容量、则还必须将订阅续订至少一年。

*新订阅是否可以灵活地随新的年度期限一起提供？*

可以，新订阅可以与任何现有订阅分开使用新条款。

*租户订阅条款是否可以超出合作伙伴的订阅期限？*

租户订阅可以超出合作伙伴当前的Keystone服务期限。创建订阅时以及在使用情况报告中都会显示警告。

*是否可以在同一个ONTAP 集群上混用多个订阅？*

不会，每个集群都分配给一个特定订阅。

*谁负责监控和操作？*

对于 NetApp 运营的服务， NetApp 负责远程监控基础架构，以便按照约定的预期交付服务。

对于合作伙伴运营的服务，合作伙伴负责远程监控基础架构，以便根据约定的预期交付服务。

对于客户运营的服务，客户负责监控基础架构并向 NetApp 提出任何问题。

*如果我提前终止服务会发生什么情况？*

最低服务承诺为 12 个月。如果您提前取消服务，则需要提前支付剩余价值。

*初始期限完成后是否有机会转换为购买？*否此优惠不包括转换为购买的选项。此外，以前购买的 NetApp 产品不在此计划范围内。

*是否可以请求特定软件版本？*

否NetApp Keystone 已对其所有客户群的软件版本进行标准化。

*是否会收到有关软件升级的通知？*

是的。所有维护 / 升级活动均由 NetApp Keystone 成功经理在双方同意的时间与客户进行沟通和计划。
