---
sidebar: sidebar 
permalink: nkfsosm_performance.html 
keywords: netapp, keystone, performance, 
summary: Keystone Flex 订阅性能 
---
= 性能服务级别
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone 灵活订阅（ Flex 订阅）可按预定义的性能级别提供容量。

每个性能服务级别均通过其 I/O 密度来定义，该密度是指性能（每秒输入 / 输出操作数 IOPS ）与已用存储（已存储数据的 TiB ）（即 IOPS/TiB ）之比。

由 Flex 订阅服务管理的每个卷都与一个性能服务级别相关联。在计算卷的 I/O 密度时会考虑相应卷上使用的所有 I/O 操作和所有已用存储。

下表定义了性能服务级别。



== 不同存储类型的性能服务级别

此处列出了文件，块和对象存储的服务级别。

报告卷级别的 I/O 密度计算，以显示前一周的峰值 I/O 密度。峰值性能是按每小时时间间隔确定的。每个月都会按卷生成 I/O 密度报告，以衡量是否符合相应的服务级别。



=== 文件共享

* 支持的协议 * ： NFS 和 CIFS

|===


| * 服务级别 * | * 至尊 * | * 高级版 * | * 标准 * | * 值 * 


| * 工作负载类型 * | 分析，数据库 | VDI ，虚拟化应用程序，软件开发 | 文件共享， Web 服务器 | 备份 


| * 目标 IOPS/TiB* | 6,144 | 2 ， 048 | 128. | 不适用 


| * 最大 IOPS/TiB* | 12,288 | 4,096 | 512 | 不适用 


| * 最大吞吐量 MBps （ 32 KB/IOP ） * | 384 | 128. | 16. | 不适用 


| * 延迟 * | 小于 1 毫秒 | 小于 2 毫秒 | 小于 17 毫秒 | 不适用 


.2+| * 最小容量 *^1 ， 2^ 4+| 100 TiB^1^ 


| 15 TiB^2^ | 25 TiB^2^ | 50 TiB^2^ | 50 TiB^2^ 
|===

NOTE: ^1^ 为 NetApp 直接商机提供的任何文件共享和块性能服务级别的组合，最小期限为一年，最小容量为 100 TiB 。^2^ 为渠道主导的商机选择的每个服务层的最小一年期限和最小规定容量。



=== 块存储

* 支持的协议 * ： FC 和 iSCSI

|===


| * 服务级别 * | * 至尊 * | * 高级版 * | * 标准 * 


| * 工作负载类型 * | HPC | 视频监控 | 备份 


| * 目标 IOPS/TiB* 3+| 不适用 


| * 最大 IOPS/TiB* | 5.500 | 4 ， 000 | 不适用 


| * 最大吞吐量 MBps （ 32 KB/IOP ） * | 43 | 31 | 不适用 


| * 延迟 * | <0.5 毫秒 | <0.5 毫秒 | 不适用 


| * 最小容量 *^1 ， 2^ | 100 TiB^3^ | 100 TiB^3^ | 300 TiB^3^ 
|===

NOTE: ^1^ 为 NetApp 直接商机提供的任何文件共享和块性能服务级别的组合，最小期限为一年，最小容量为 100 TiB 。^2^ 为渠道主导的商机选择的每个服务层的最小一年期限和最小规定容量。^3^ 为任一商机类型选择的每个服务层的最小一年期限和最小指定容量。



=== 对象存储

* 支持的协议 * ： S3

|===


| * 服务级别 * | 对象 


| * 工作负载类型 * | 介质存储库，归档 


| * 目标 IOPS/TiB* | 不适用 


| * 最大 IOPS/TiB* | 不适用 


| * 最大吞吐量 MBps （ 32 KB/IOP ） * | 不适用 


| * 延迟 * | 不适用 


| * 最小容量 *^1 ， 2^ | 500 TiB^3^ 
|===

NOTE: ^1^ 为 NetApp 直接商机提供的任何文件共享和块性能服务级别的组合，最小期限为一年，最小容量为 100 TiB 。^2^ 为渠道主导的商机选择的每个服务层的最小一年期限和最小规定容量。^3^ 为任一商机类型选择的每个服务层的最小一年期限和最小指定容量。
