---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: NetApp Keystone 服务
    url: "/index.html"
    entries:
    - title: 服务条款和问题描述
      url: "/nkfsosm_service_terms_and_description_overview.html"
      entries:
      - title: 服务容量定义
        url: "/nkfsosm_keystone_service_capacity_definitions.html"
      - title: Keystone中的服务级别
        url: "/nkfsosm_performance.html"
      - title: 服务级别指标和定义
        url: "/nkfsosm_service_level_metrics_and_definitions.html"
      - title: Keystone中的自适应服务质量
        url: "/aqos-kfs.html"
      - title: 计费
        url: "/nkfsosm_kfs_billing.html"
      - title: 数据保护
        url: "/nkfsosm_data_protection.html"
      - title: 分层
        url: "/nkfsosm_tiering.html"
      - title: 不可退回的磁盘
        url: "/nkfsosm_nrd.html"
      - title: 美国公民支持
        url: "/nkfsosm_uscs.html"
      - title: Keystone和Equinix
        url: "/nkfsosm_equinix.html"
    - title: 运营模式和职责
      url: "/nkfsosm_overview.html"
    - title: 租户和多租户
      url: "/nkfsosm_tenancy_overview.html"
    - title: Keystone基础架构
      url: "/nkfsosm_keystone_service_delivery_architecture_overview.html"
    - title: 站点要求
      url: "/nkfsosm_site_requirements.html"
    - title: 操作
      url: "/nkfsosm_netapp_global_services_and_support_center_@gssc@.html"
    - title: Keystone和Active IQ 数字顾问
      url: "/nkfsosm-keystone-and-aiq.html"
      entries:
      - title: 从Active IQ 数字顾问查看和生成报告
        url: "/aiq-keystone-details.html"
  - title: 发行说明
    entries:
    - title: 新增功能
      url: "/rn_whats_new.html"
    - title: 已修复的问题
      url: "/rn_fixed_issues.html"
    - title: 已知问题
      url: "/rn_known_issues.html"
  - title: Keystone订阅常见问题解答
    url: "/nkfsfaq_overview.html"
    entries:
    - title: Keystone订阅
      url: "/nkfsfaq_keystone_subscription.html"
    - title: 服务优惠详细信息
      url: "/nkfsfaq_service_offer_details.html"
    - title: 操作模式
      url: "/nkfsfaq_operating_models.html"
  - title: 法律声明
    url: "/legal-notices.html"
