---
sidebar: sidebar 
permalink: seapiref_subtenants.html 
keywords: netapp, keystone, subtenants, 
summary: Keystone 子租户 
---
= 子租户
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用下表中列出的方法检索，创建，修改和删除子租户。

|===
| HTTP 方法 | 路径 | Description 


| `获取` | ` /v2.1/ 子租户` | 检索子租户。 


| `获取` | ` /v2.1/subteners/ ｛ id ｝` | 按子租户 ID 检索子租户。 


| `发布` | ` /v2.1/ 子租户`` | 创建新的子租户。 


| `PUT` | ` /v2.1/subteners/ ｛ id ｝` | 修改子租户的详细信息。您可以修改子租户的名称。 


| `d删除` | ` /v2.1/subteners/ ｛ id ｝` | 删除子租户。 
|===


=== 子租户属性

下表列出了子租户属性。

|===
| 属性 | Type | Description 


| `id` | string | 子租户的唯一标识符。 


| `名称` | string | 子租户名称。 


| `代码` | string | 客户指定的（或默认的）代码，表示子租户。 


| `tenant_id` | string | 子租户所属租户的标识符。 
|===


=== 检索所有子租户

使用下表中列出的方法检索所有子租户或所有子租户的一部分。指定 `tenant_id` 将仅返回属于该租户的子租户。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `获取` | ` /v2.1/ 子租户` | 检索子租户。 | `tenant_id` ：（可选）返回属于指定租户的子租户。偏移和限制—请参见 
|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
none
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 202,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 2,
    "records": [      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "mysubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      },
      {
        "id": "5d9144f3869caefed0f39f82",
        "description": "",
        "name": "Mysubtenant2",
        "code": "myothersubtenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== 按 ID 检索子租户

使用下面列出的方法按 ID 检索子租户。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `获取` | ` /v2.1/subteners/ ｛ id ｝` | 检索 ID 指定的子租户。 | `id （ string ）` ：子租户的唯一标识符。 
|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
none
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "subtenantcode",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== 创建子租户

使用下表中列出的方法创建子租户。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `发布` | ` /v2.1/ 子租户` | 创建新的子租户。 | 无 
|===
所需请求正文属性： `name` ， `code` ， `tenant_id`

* 请求正文示例： *

....
{
  "name": "MySubtenant",
  "code": "mynewsubtenant",
  "tenant_id": "5ed5ac802c356a0001a735af"
}
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== 按 ID 修改子租户

使用下表中列出的方法按 ID 修改子租户。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `PUT` | ` /v2.1/subteners/ ｛ id ｝` | 修改 ID 指定的子租户。您可以更改子租户名称。 | `id （ string ）` ：子租户的唯一标识符。 
|===
所需的请求正文属性： `name`

* 请求正文示例： *

....
{
  "name": "MyModifiedSubtenant"
}
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== 按 ID 删除子租户

使用下表中列出的方法按 ID 删除子租户。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `d删除` | ` /v2.1/subteners/ ｛ id ｝` | 删除此 ID 指定的子租户。 | `id （ string ）` ：子租户的唯一标识符。 
|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
none
....
* 响应正文示例： *

....
No content for succesful delete
....