---
sidebar: sidebar 
permalink: seapiref_service_requests.html 
keywords: netapp, keystone, service, requests, 
summary: Keystone 服务请求 
---
= 服务请求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用下表中列出的方法创建和检索服务请求。

|===
| HTTP 方法 | 路径 | Description 


| `获取` | ` /v2.1/tenant/ ｛ tenant_id ｝ /servicerequests` | 检索服务请求。 


| `获取` | ` /v2.1/tenant/ ｛ tenant_id ｝ / 服务要求 / ｛ id ｝` | 按 ID 检索服务请求。 


| `发布` | ` /v2.1/tenant/ ｛ tenant_id ｝ /servicereques/` | 创建服务请求。 


| `获取` | ` /v2.1/tenant/｛ tenant_id ｝ /servicerequies/categories` | 检索服务请求类别。 
|===


=== 服务请求属性

下表列出了服务请求属性。

|===
| 属性 | Type | Description 


| `ID` | string | 服务请求的标识符。例如： `s Q0035952014 。` 


| `sSubject` | string | 服务请求的主题。 


| `注释` | string | 对服务请求的注释 


| `类别` | string | 请求的类别：备份，灾难恢复，技术，其他或订阅。 


| `优先级` | string | 服务请求的优先级：极低，低，正常，高或紧急。 


| `ssubscription` | string | Zuora 订阅编号。 


| `承诺` | –  a| 
订阅承诺详细信息，包括：

* 服务级别（字符串）：服务级别：标准，高级或至尊。
* new_commitment （整型）：需要新的总容量。




| `分区` | string | 分区名称。 


| `ssubtenant_id` | string | 子租户标识符。 


| `storage_object_type` | string | 存储对象类型：文件服务器或块存储。 


| `storage_object_id` | string | 存储对象的标识符。例如： `5d2fb0fb4f47df00015274e3` 


| `sservice_type` | string | 服务类型：文件服务，块存储或对象存储。 
|===


=== 检索服务请求

使用下表中列出的方法检索指定租户的服务请求类别。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `获取`` | ` /v2.1/tenant/ ｛ tenant_id ｝ /servicerequests` | 检索服务请求。 | `tenant_id` ：（可选）返回指定租户的服务请求。`offset` 和 `limit` —请参见 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["通用分页"] 
|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
none
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 34,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 6,
    "limit": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


=== 按 ID 检索服务请求

使用下表中列出的方法按服务请求 ID 检索服务请求。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `获取` | ` /v2.1/tenant/ ｛ tenant_id ｝ / 服务要求 / ｛ id ｝` | 按 ID 检索服务请求。  a| 
* `tenant_id` ：租户 ID
* `id` ：服务请求 ID 例如： SRQ0035952014


|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
none
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


=== 创建服务请求

使用下表中列出的方法创建服务请求。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `发布` | ` /v2.1/tenant/｛ tenant_id ｝ /servicerequies/categories` | 创建服务请求。 | `tenant_id` ：租户标识符。 
|===
所需请求正文属性：所需属性取决于服务请求的类别。下表列出了请求正文属性。

|===
| 类别 | Required 


| 订阅。 | `ssubscription` and `commitment` 


| 灾难恢复 | `storage_object_type` ， `ssubtenant_id` 和 `storage_object_id` 


| 技术 | `ssubtenant_id` 和 `sservice_type` 如果 `sservice_type` 是文件服务或块存储，则需要区域。 


| 其他 | 分区 
|===
* 请求正文示例： *

....
{
  "subject": "string",
  "comment": "string",
  "category": "subscription",
  "priority": "Normal",
  "subscription": "A-S00003969",
  "commitment": {
    "service_level": "standard",
    "new_commitment": 10
  },
  "zone": "au-east1-a",
  "subtenant_id": "5d2fb0fb4f47df00015274e3",
  "storage_object_type": "fileserver",
  "storage_object_id": "5d2fb0fb4f47df00015274e3",
  "service_type": "File Services"
}
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "string",
        "subject": "string",
        "description": "string",
        "status": "New",
        "priority": "Normal",
        "createdDate": "2020-05-12T03:18:25+0000",
        "UpdatedDate": "2020-05-12T03:18:25+0000"
      }
    ]
  }
....


=== 检索服务请求类别

下表列出了指定租户的检索服务请求类别。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `获取` | ` /v2.1/tenant/｛ tenant_id ｝ /servicerequies/categories` | 检索服务请求类别。 | `tenant_id ：` （可选）返回指定租户的服务请求。 
|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
none
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. Returned 5 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 5,
    "records": [
      {
        "key": "dr",
        "value": "Disaster Recovery Failover"
      },
      {
        "key": "technical",
        "value": "Technical Issue"
      },
      {
        "key": "other",
        "value": "Other"
      },
      {
        "key": "subscription",
        "value": "Subscription Management"
      },
      {
        "key": "backup",
        "value": "Backup Restore"
      }
    ]
  }
}
....