---
sidebar: sidebar 
permalink: seapiref_service_levels.html 
keywords: netapp, keystone, service, levels, 
summary: Keystone 服务级别 
---
= 服务级别
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用下表中列出的方法检索，创建，修改和删除服务级别。

|===
| HTTP 方法 | 路径 | Description 


| `获取` | ` /v2.1/ServiceLevels` | 检索所有服务级别。 


| `获取` | ` /v2.1/ServiceLevers/ ｛ id ｝` | 按 ID 检索服务级别。 


| `发布` | ` /v2.1/ServiceLevels` | 创建新的服务级别。 


| `PUT` | ` /v2.1/ServiceLevers/ ｛ id ｝` | 按 ID 修改服务级别详细信息。 


| `d删除` | ` /v2.1/ServiceLevers/ ｛ id ｝` | 删除服务级别。 
|===


=== 服务级别属性

下表列出了服务级别属性。

|===
| 属性 | Type | Description 


| `id` | string | 服务级别的唯一标识符。 


| `名称` | string | 服务级别名称。 


| 问题描述` | string | 服务级别的问题描述。 


| `policy_name` | string | 服务级别服务质量（ QoS ）名称。允许的值： NSE_value ， nse_standard ， nse_performance 和 nse_Extreme 。 


| `可用` | 布尔值 | 指示服务级别是否可供使用。 


| `祖父系` | 布尔值 | 指示服务级别是否已停用。 


| `pease_IOPS_per_TB` | 整型 | 每 TiB 的最大可能 IOPS 。 


| `expected_IOPS_per_TB` | 整型 | 每 TiB 的最小预期 IOPS 。 


| `abory_min_IOPS` | 整型 | 当预期 IOPS 小于此值时用作覆盖的绝对最小 IOPS 。 


| `pease_IOPS_allocation` | string | 峰值 IOPS 分配。允许值： allocated_space 和 used_space 。 


| `io_block_size_KB` | 整型 | I/O 块大小（ KiB ）。 


| `min_size_GB` | 整型 | 最小大小（ GiB ）。 


| `max_size_GB` | 整型 | 最大大小（ GiB ）。 


| `max_pease_IOPS` | 整型 | 服务级别的最大峰值 IOPS 。 


| `max_expected_IOPS` | 整型 | 最大预期 IOPS 。 


| `autogrow_max_percent` | 整型 | 自动增长最大百分比。 


| `ontap_aggregates` | –  a| 
ONTAP 聚合的列表。ONTAP 聚合包括：

* `cluster_UIID ： ONTAP 集群 UUID`
* `aggr_name ： ONTAP 聚合名称`
* `aggr_uuid ： ONTAP 聚合 UUID`
* `node_name ： ONTAP 集群节点名称` 例如：


[listing]
----
"ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ]
----


| `primary_volume_defaults` | –  a| 
* snapshot_auto_delete_target_free_space （整型）：此选项指定必须停止自动删除 Snapshot 副本的可用空间百分比。
* auto_size_mode （字符串）：卷的自动调整大小模式。允许的值： off ， grow ， grow_shrink ，例如：


[listing]
----
"primary_volume_defaults": {    "snapshot_auto_delete_target_free_space": 3,    "auto_size_mode": "grow_shrink"
----
|===


=== 检索服务级别

使用下表中列出的方法检索所有服务级别。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `获取` | ` /v2.1/ServiceLevels` | 检索所有服务级别。 | 无 
|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
none
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. Returned 3 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 3,
    "records": [
      {
        "name": "standard",
        "description": "Best suited for general purpose workloads",
        "slo": "1000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 40000,
        "max_expected_iops": 28000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 875
      },
      {
        "name": "extreme",
        "description": "Best suited for performance-critical workloads",
        "slo": "12000IOPS/TB",
        "min_size": 91625968981,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 500,
        "peak_iops_per_tb": 12000,
        "expected_iops_per_tb": 8000,
        "max_peak_iops": 120000,
        "max_expected_iops": 60000,
        "max_peak_throughput": 3750,
        "max_expected_throughput": 1875
      },
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4000,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


=== 按名称检索服务级别

使用下表中列出的方法按名称检索服务级别。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `获取` | ` /v2.1/ServiceLevers/ ｛ name ｝` | 按名称检索服务级别。 | `name （ string ）` ：服务级别的名称。 
|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
none
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4096IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4096,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


=== 创建服务级别

使用下表中列出的方法创建服务级别。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `发布` | ` /v2.1/ServiceLevels` | 创建服务级别。 | 无 
|===
所需的请求正文属性： `name` ， `policy_name`

* 请求正文示例： *

....
{
  "name": "MyServiceLevelName",
  "description": "My new service level description",
  "policy_name": "nse_value",
  "available": true,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "name": "MyServiceLevelName",
        "description": "My new service level description",
        "slo": "1000IOPS/TB",
        "min_size": 0,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 20000,
        "max_expected_iops": 5000,
        "max_peak_throughput": 625,
        "max_expected_throughput": 156
      }
    ]
  }
}
....


=== 修改服务级别

使用下表中列出的方法修改服务级别。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `PUT` | ` /v2.1/ServiceLevers/ ｛ name ｝` | 修改服务级别的详细信息。 | `name （ string ）` ：服务级别的名称。 
|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
{
  "name": "MyNewServiceLevelName",
  "description": "Service level description",
  "policy_name": "nse_value",
  "available": false,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
* 响应正文示例： *

....
TBA
....


=== 按 ID 删除服务级别

使用下表中列出的方法按 ID 删除服务级别。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `d删除` | ` /v2.1/ServiceLevers/ ｛ name ｝` | 删除 ID 标识的服务级别。 | `name （ string ）` ：服务级别的名称。 
|===
* 请求正文示例： *

....
none
....
* 响应正文示例： *

....
No content for succesful delete
....