---
sidebar: sidebar 
permalink: seapiref_backups_apis.html 
keywords: netapp, keystone, backups, apis, 
summary: Keystone 备份 API 
---
= 备份 API
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用备份 API 查看和管理环境中卷（文件共享和磁盘）的快照（备份或恢复点）。

[cols="1,1,3,2"]
|===
| HTTP 动词 | 路径 | Description | 必需参数 / 请求正文 


 a| 
`获取`
 a| 
` v2.1/backups`
| 您可以检索为租户下的子租户创建的所有卷的所有备份对象的详细信息。检索源卷和备份对象的详细信息，例如备份策略，分区和标记。  a| 
`offset` ：开始收集结果集之前要跳过的项数。`limit` ：要返回的项数。



 a| 
`获取`
 a| 
` /v2.1/backups/ ｛ id ｝`
| 您可以检索为租户下的子租户的卷创建的特定备份对象的详细信息。根据输入的 ID 检索源卷和备份对象的详细信息，例如备份策略，分区和标记。  a| 
`id` ：备份对象的 ID 。



 a| 
`获取`
 a| 
` /v2.1/backup/ ｛ id ｝ /` `recovery_points`
| 您可以检索特定备份对象的所有恢复点的详细信息。系统将检索详细信息，例如时间戳和名称。  a| 
`id` ：备份对象的 ID 。



 a| 
`获取`
 a| 
` /v2.1/backup/ ｛ id ｝ /` `recovery_points/ ｛ name ｝`
| 您可以检索特定备份对象的任何恢复点的详细信息。系统将检索详细信息，例如时间戳和名称。  a| 
`id` ：备份对象的 ID 。`name` ：恢复点的名称。



 a| 
`发布`
 a| 
` v2.1/backups`
| 您可以为特定源卷创建备份对象。在请求正文中添加值，以使用指定参数创建备份对象，例如备份策略，要保留的备份副本数以及源资源 ID 。  a| 
`` ｛ "primary_resource_type" ： "< 资源类型 >" ， "source_resource_id" ： "<ID>" ， "backup_zone" ： "<Backup Zone>" ， "backup_policy" ： ｛ "daily_backups_to_keep" ： < 要保留的每日备份数 > ， "weekly_backups_to_keep" ： <key_number> ， "<only" ： < 保留的每月备份数 > ， "<key_backups" ： <key_task_als" ： < 保留的 "<key_als" ， "<number> ： < 保留 "<key_backups" ： <key_als" ： <key_als" ， "keep" ， "keep" "<Tag N>" ｝ ｝ ``



 a| 
`发布`
 a| 
` /v2.1/backups/｛ id ｝ /tags`
| 您可以为子租户的备份对象创建或替换标记。在请求正文中以 "key ： value pair" 格式添加备份对象的 ID 和标记值。  a| 
`id` ：备份对象的 ID 。`` ｛ "key1" ： "< 标记 1>" ， "key2" ： "< 标记 2>" ， "keyN" ： "< 标记 N>" ｝ ``



 a| 
`修补程序`
 a| 
` /v2.1/backups/ ｛ id ｝`
 a| 
您可以根据卷的 ID 修改卷的任何备份对象。添加备份对象的 ID 以及要在请求正文中修改的值，例如备份策略详细信息，要保留的备份数以及源资源 ID 。

[NOTE]
====
您可以通过在 `patch` 请求中将 `ssource_resource_id` 参数的值设置为空来使备份对象成为孤立对象。此操作将删除 SnapMirror 关系，但会保留备份卷及其恢复点。

==== a| 
`id` ：备份对象的 ID 。`` ｛ "source_resource_id" ： "<Resource ID>" ， "backup_policy" ： ｛ "daily_backups_to_keep" ： < 要保留的每日备份数 > ， "weekly_backups_to_keep" ： < 要保留的每月备份数 > ， "<key_backups_to_keep" `` ： < 要保留的每周备份数 > ， "<key_task_task_tags ： < 要保留的每月备份数 > ， "<"<key_task_task_task_task> ， "<"<"<key_task_task_keep" ： < 月备份数 > ， "<"<key_task_task_task> ： <



 a| 
`d删除`
 a| 
` /v2.1/backups/ ｛ id ｝`
| 您可以删除卷的任何备份对象以及所有恢复点。  a| 
`id` ：备份对象的 ID 。



 a| 
`d删除`
 a| 
` /v2.1/backup/ ｛ id ｝ /` `recovery_points/ ｛ name ｝`
| 您可以删除卷的特定备份对象中的任何恢复点。  a| 
`id` ：备份对象的 ID 。`name` ：恢复点的名称。

|===