---
sidebar: sidebar 
permalink: seapiref_zones.html 
keywords: netapp, keystone, zones, 
summary: Keystone 分区 
---
= 分区
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用下表中列出的方法创建，修改和删除分区。有关可用于检索区域的 API ，请参见（使用者）管理 API 。

|===
| HTTP 方法 | 路径 | Description 


| `发布` | ` v2.1/zones` | 创建新分区。 


| `PUT` | ` /v2.1/zones/ ｛ name ｝` | 修改分区的详细信息。 


| `d删除` | ` /v2.1/zones/ ｛ name ｝` | 删除分区。 
|===


=== 分区属性

下表列出了分区属性。

|===
| 属性 | Type | Description 


| `id` | string | 分区的唯一标识符。 


| `名称` | string | 分区名称。 


| 问题描述` | string | 分区的问题描述。 


| `reGion_name` | string | 分区所在区域的名称。 
|===


=== 检索所有分区

使用下表中列出的方法检索所有分区或部分分区。指定区域将仅返回属于该租户的块存储。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `获取` | ` v2.1/zones` | 检索分区。 | （可选）区域名称（字符串） `offset` 和 `limit` —请参见 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["通用分页"] 
|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
none
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 5,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 2,
    "limit": 1,
    "records": [
      {
        "id": "5ce5d919b68d3b82dc34bef2",
        "name": "au-west1-a",
        "description": "au-west1-a",
        "region": "au-west1"
      }
    ]
  }
....


=== 按名称检索分区

使用下表中列出的方法按分区名称检索分区。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `获取` | ` /v2.1/zones/ ｛ name ｝` | 按名称检索分区。 | `Name （ string ）` ：分区名称 
|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
none
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ce5d919b68d3b82dc34bef2",
        "name": "au-west1-a",
        "description": "au-west1-a",
        "region": "au-west1"
      }
    ]
  }
}
....


=== 创建分区

使用下表中列出的方法创建分区。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `发布` | ` v2.1/zones` | 在区域中创建新分区。 | 无 
|===
所需的请求正文属性： `name` ，问题描述` ， `reGion_name`

* 请求正文示例： *

....
{
  "name": "MyZoneName",
  "description": "DescriptionOfMyZone",
  "region_name": "MyRegionName"
}
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61741c9b64790001fe9663",
        "name": "MyZoneName",
        "description": "DescriptionOfMyZone",
        "region": "MyRegionName"
      }
    ]
  }
}
....


=== 修改分区

使用下表中列出的方法修改分区。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `PUT` | ` /v2.1/zones ｛ name ｝` | 修改以名称标识的分区。 | `name （ string ）` ：分区的名称。 
|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
{
  "name": "MyZoneName",
  "description": "NewDescriptionOfMyZone"
}
....
* 响应正文示例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61741c9b64790001fe9663",
        "name": "MyZoneName",
        "description": "NewDescriptionOfMyZone",
        "region": "MyRegionName"
      }
    ]
  }
}
....


=== 删除分区

使用下表中列出的方法删除分区。

|===
| HTTP 方法 | 路径 | Description | Parameters 


| `d删除` | ` /v2.1/zones ｛ name ｝` | 删除通过名称标识的单个分区。必须先删除区域中的所有存储资源。 | `name （ string ）` ：分区的名称。 
|===
所需的请求正文属性： `none`

* 请求正文示例： *

....
none
....
* 响应正文示例： *

成功删除后，不会返回任何内容。
