---
sidebar: sidebar 
permalink: seapiref_block_storage_apis.html 
keywords: netapp, keystone, block storage, block stores, disks, host groups, initiators, apis 
summary: Keystone 块存储 API 
---
= 块存储 API
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用块存储 API 查看和管理块存储。

在创建磁盘之前，必须创建块存储。创建磁盘时，您必须创建主机组或选择现有主机组才能访问该磁盘。有关详细信息，请参见 link:sewebiug_working_with_block_storage_overview.html["使用块存储"]。



== 块存储

您可以使用块存储 API 检索和管理块存储。

[cols="1,1,3,2"]
|===
| HTTP 动词 | 路径 | Description | 必需参数 / 请求正文 


 a| 
`获取`
 a| 
` v2.1/blockstore`
| 您可以检索所有块存储的详细信息。检索块存储的详细信息，例如块存储 ID ， IP 地址，区域，分区，子网 ID ， 和标记。  a| 
`offset` ：开始收集结果集之前要跳过的项数。`limit` ：要返回的项数。



 a| 
`获取`
 a| 
` /v2.1/blockstores/｛ id ｝`
| 您可以检索特定块存储的详细信息。根据输入的 ID 检索块存储的详细信息，例如 IP 地址，区域，分区，子网 ID 和标记。  a| 
`id` ：块存储的 ID 。



 a| 
`发布`
 a| 
` v2.1/blockstore`
| 您可以创建块存储。在请求正文中添加值以使用指定参数创建块存储，例如服务协议，子租户 ID ，区域，子网 ID 和标记。  a| 
`ssubtenant_id` ：子租户的 ID 。`zone` ：分区的名称。`ssubnet_id` ：子网的 ID 。



 a| 
`发布`
 a| 
` /v2.1/blockstores/｛ id ｝ /` `标记`
| 您可以为块存储创建或替换标记。在请求正文中添加块存储的 ID 以及 "key ： value pair" 格式的标记值。  a| 
`id` ：块存储的 ID 。



 a| 
`PUT`
 a| 
` /v2.1/blockstores/｛ id ｝`
| 您可以根据任何块存储的 ID 来修改其。添加块存储的 ID 以及要在请求正文中修改的值，例如分区，服务协议和标记。  a| 
`id` ：块存储的 ID 。



 a| 
`d删除`
 a| 
` /v2.1/blockstores/｛ id ｝`
 a| 
您可以按 ID 删除任何块存储。
 a| 
`id` ：块存储的 ID 。

|===

NOTE: 删除块存储之前，应删除映射到该块存储的所有磁盘。



== Disks

您可以使用磁盘 API 检索和管理磁盘。

[cols="1,1,3,2"]
|===
| HTTP 动词 | 路径 | Description | 必需参数 / 请求正文 


 a| 
`获取`
 a| 
` v2.1/disks`
| 您可以检索所有磁盘的详细信息。检索磁盘的详细信息，例如块存储 ID ，名称，磁盘路径，协议，快照策略， 和标记。  a| 
`offset` ：开始收集结果集之前要跳过的项数。`limit` ：要返回的项数。



 a| 
`获取`
 a| 
` /v2.1/disks/｛ id ｝`
| 您可以检索特定磁盘的详细信息。检索磁盘的详细信息，例如块存储 ID ，名称，磁盘路径，协议，快照策略， 和标记。  a| 
`id` ：磁盘的 ID 。



 a| 
`发布`
 a| 
` v2.1/disks`
| 您可以创建磁盘。在请求正文中添加值以使用指定参数创建磁盘，例如子租户 ID ，分区，名称，磁盘路径，快照策略， 备份策略和标记。  a| 
`ssubtenant_id` ：子租户的 ID 。`zone` ：分区的名称。`name` ：磁盘的名称。`disk_path` ：磁盘的路径。`protocol` ：用于块设备访问的存储协议。`OS_type` ：主机操作系统的类型。`hostgroup_mappings` ：主机组映射。`sservice_level` ：适用的服务级别名称：标准，高级，高级分层，至尊或至尊分层。`size_GB` ：磁盘大小，以 GB 为单位。



 a| 
`发布`
 a| 
` /v2.1/disks/ ｛ id ｝ /` `snapshot/ ｛ name ｝`
| 您可以创建磁盘快照。  a| 
`id` ：磁盘的 ID 。`name` ：快照的名称。



 a| 
`发布`
 a| 
` /v2.1/disks/｛ id ｝ /` `标记`
| 您可以为磁盘创建或替换标记。在请求正文中以 "key ： value pair" 格式添加磁盘 ID 和标记值。  a| 
`id` ：磁盘的 ID 。



 a| 
`PUT`
 a| 
` /v2.1/disks/｛ id ｝`
| 您可以根据磁盘 ID 修改任何磁盘。添加磁盘的 ID 以及要在请求正文中修改的值，例如名称，服务级别，快照策略，备份策略和标记。  a| 
`id` ：磁盘的 ID 。`hostgroup_mappings` ：主机组映射。



 a| 
`d删除`
 a| 
` /v2.1/disks/｛ id ｝`
| 您可以按 ID 删除任何磁盘。  a| 
`id` ：磁盘的 ID 。



 a| 
`d删除`
 a| 
` /v2.1/disks/ ｛ id ｝ /` `snapshot/ ｛ name ｝`
| 您可以按磁盘 ID 和快照名称删除磁盘的任何快照。  a| 
`id` ：磁盘的 ID 。`name` ：快照的名称。

|===


== 主机组

对磁盘的访问控制通过主机组进行管理。您可以使用主机组 API 检索和管理主机组。

[cols="1,1,3,2"]
|===
| HTTP 动词 | 路径 | Description | 必需参数 / 请求正文 


 a| 
`获取`
 a| 
` /v2.1/hostgroups`
| 您可以检索所有主机组的详细信息。检索主机组的详细信息，例如名称，子租户详细信息，租户详细信息，区域， 协议，启动程序，使用主机组的磁盘以及标记。  a| 
`offset` ：开始收集结果集之前要跳过的项数。`limit` ：要返回的项数。



 a| 
`获取`
 a| 
` /v2.1/hostgroups/ ｛ id ｝`
| 您可以检索特定主机组的详细信息。检索主机组的详细信息，例如名称，子租户详细信息，租户详细信息，区域， 协议，启动程序，使用主机组的磁盘以及基于输入的 ID 的标记。  a| 
`id` ：主机组的 ID 。



 a| 
`发布`
 a| 
` /v2.1/hostgroups`
| 您可以创建主机组。在请求正文中添加值以使用指定参数创建主机组，例如名称，子租户 ID ，区域，协议， 启动程序和标记。  a| 
`name` ：主机组的名称。`ssubtenant_id` ：子租户的 ID 。`zone` ：分区的名称。`protocol` ：用于块设备访问的存储协议。`OS_type` ：主机操作系统的类型。



 a| 
`发布`
 a| 
` /v2.1/hostgroups/ ｛ id ｝ /` `标记`
| 您可以为主机组创建或替换标记。在请求正文中以 "key ： value pair" 格式添加主机组的 ID 以及标记的值。  a| 
`id` ：主机组的 ID 。



 a| 
`d删除`
 a| 
` /v2.1/hostgroups/ ｛ id ｝`
| 您可以按 ID 删除任何主机组。  a| 
`id` ：主机组的 ID 。

|===


== 主机组中的启动程序

您可以使用主机组 API 检索和管理映射到主机组的启动程序。

[cols="1,1,3,2"]
|===
| HTTP 动词 | 路径 | Description | 必需参数 / 请求正文 


 a| 
`获取`
 a| 
` /v2.1/hostgroups/ ｛ id ｝ /` `启动程序`
| 您可以检索所有启动程序的详细信息。检索启动程序及其别名。  a| 
`id` ：主机组的 ID 。



 a| 
`获取`
 a| 
` /v2.1/hostgroups/ ｛ id ｝ /` `启动程序 / ｛ alias ｝`
| 您可以检索特定启动程序的详细信息。根据输入的 ID 和别名检索启动程序。  a| 
`id` ：主机组的 ID 。`alias` ：启动程序的别名。



 a| 
`发布`
 a| 
` /v2.1/hostgroups/ ｛ id ｝ /` `启动程序`
 a| 
您可以为主机组创建启动程序。在请求正文中添加启动程序及其别名的值，以便为主机组创建启动程序。
 a| 
`id` ：主机组的 ID 。`alias` ：启动程序的别名。`initiator` ：启动程序（ iSCSI 限定名称或 FC WWPN ）。



 a| 
`修补程序`
 a| 
` /v2.1/hostgroups/ ｛ id ｝ /` `启动程序 / ｛ alias ｝`
| 您可以修改启动程序。在请求正文中添加新启动程序。  a| 
`id` ：主机组的 ID 。`alias` ：启动程序的别名。`initiator` ：启动程序（ iSCSI 限定名称或 FC WWPN ）。`



 a| 
`d删除`
 a| 
` /v2.1/hostgroups/ ｛ id ｝ /` `启动程序 / ｛ alias ｝`
 a| 
您可以按主机组的 ID 和启动程序的别名删除启动程序。
 a| 
`id` ：主机组的 ID 。`alias` ：启动程序的别名。

|===
[NOTE]
====
将启动程序添加到主机组时，启动程序应与主机组协议匹配。对于采用 iSCSI 协议的主机组，应使用 IQN ；对于采用 FC 协议的主机组，应使用 WWPN 。

从主机组中删除启动程序会影响该主机组映射到的所有磁盘。

====