---
sidebar: sidebar 
permalink: sewebiug_managing_subscriptions.html 
keywords: netapp, keystone, managing, subscriptions, 
summary: 管理订阅的 Keystone 
---
= 管理订阅
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
管理订阅包括为NetApp Keystone 订阅和租户订阅服务分配服务级别、或者使用NetApp服务引擎界面为服务级别分配和更改容量。

服务提供商/合作伙伴与NetApp之间的关系以及租户订阅所代表的订阅服务代表服务提供商与其租户和子租户(最终客户)之间的关系。当NetApp管理员或GSSC为合作伙伴和租户创建Keystone订阅服务时、这意味着存储分配已完成。但是，除非创建服务级别并完成相应的容量分配，否则子租户或最终客户将无法使用存储。合作伙伴管理员可以为其Keystone订阅服务和租户订阅管理存储。租户管理员只能查看其自己租户的租户订阅详细信息和服务。



== 管理Keystone订阅

如果您是合作伙伴管理员、则可以从*订阅*>* Keystone订阅*查看和管理Keystone订阅服务。* Keystone订阅*表示NetApp合作伙伴管理员创建的Keystone订阅服务。合作伙伴管理员可以查看其Keystone订阅服务并创建服务请求、以便：

* 增加订阅容量
* 将服务添加到订阅（分配服务级别和容量）


服务请求由支持团队接收和处理。

您还可以在单独的选项卡中查看和管理订阅的数据保护和高级保护服务。有关信息，请参见 link:index.html#flex-subscription["数据保护和数据保护高级"]。



=== 增加订阅容量

您可以增加任何已订阅服务级别的已承诺容量，以满足增长要求。

.步骤
. 从下拉菜单中选择要增加容量的订阅。
. 单击所需服务级别的 * 增加容量 * 。
. 指定所需的容量（以 TiB 为单位）。
. 单击*确认*。您将返回到管理Keystone订阅页面。
. 单击 * 提交更改 * 。为GSSC创建服务请求以增加容量。您可以按消息中显示的SR编号查看和跟踪服务请求的进度。有关跟踪的信息、请参见 link:sewebiug_track_a_service_request.html["跟踪服务请求"]。




=== 将服务添加到订阅

您可以将服务添加到订阅。添加服务包括为订阅分配服务级别以及为同一服务级别指定容量。

每个订阅可以具有每个服务级别之一。例如、如果您的订阅已包含Extreme和Standard服务、则可以添加Premium或Block服务。

.步骤
. 从下拉菜单中选择要添加到订阅的服务级别。
. 单击 * 添加服务 * 。
. 从下拉菜单中选择要订阅的服务级别、例如`Extreme Tiering`、然后添加要提交到服务级别的容量(以TiB为单位)。
. 单击 * 确认 * 。您将返回管理Keystone订阅页面。
. 单击 * 提交更改 * 。系统会为GSSC创建一个服务请求、以便为您的订阅分配服务级别。您可以按消息中显示的SR编号查看和跟踪服务请求的进度。


有关跟踪的信息、请参见 link:sewebiug_track_a_service_request.html["跟踪服务请求"]。



== 管理租户订阅

如果您是合作伙伴管理员，则可以从 * 订阅 * > * 租户订阅 * 创建，查看和更新租户订阅。如果您是租户管理员，则只能查看订阅。



=== 创建和编辑租户订阅

您可以为租户创建新订阅。

.步骤
. 单击 * 新建订阅 * 。
. 指定区域，区域，订阅期限，速率计划和其他详细信息。租户订阅将根据选定区域分配给 Keystone 订阅。这是因为每个 Keystone 订阅都绑定到一个分区。
+

NOTE: 您不能创建重叠的订阅。开始日期应至少为第二天，因为订阅将在指定开始日期的前一天开始。此外，它不能自当前日期起超过 30 天。

. 单击 * 创建 * 。


您不能删除任何订阅。您只能编辑现有租户订阅并添加新服务级别，增加服务级别的已提交容量以及为订阅添加标记。

如果您是合作伙伴管理员、则可以编辑租户订阅。您可以向订阅添加新的服务级别、并编辑已添加的服务级别的容量。要添加新服务级别、请执行以下步骤：

.步骤
. 通过单击`+`图标选择要编辑的订阅。
. 在*向订阅添加新服务级别*页面上、选择新服务级别并添加所需容量。如果已添加此服务级别、则无法添加或删除它。
. 单击 * 更新 * 。


您也可以通过单击订阅对应的标记图标来添加标记。

要编辑已分配给订阅的服务级别的订阅容量、请执行以下步骤：

.步骤
. 单击并单击`v`图标展开要编辑的订阅。此时将显示该订阅中的服务级别。
. 单击相应的编辑笔图标、选择要编辑的服务级别。
. 通过增加或减少以Tib为单位的容量来更改速率计划。
. 单击 * 更新 * 。

