---
sidebar: sidebar 
permalink: sewebiug_partner_service_provider.html 
keywords: netapp, service, engine, web, portal, partner, service provider 
summary: NetApp 服务引擎合作伙伴，服务提供商职能部门 
---
= 服务提供商和客户的角色和运营
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
根据您作为服务提供商或合作伙伴（可互换使用）或客户或租户（可互换使用）管理员的角色，确定 NetApp 服务引擎 Web 门户上的视图和功能。



== 您可以作为服务提供商管理员执行的活动

作为多租户环境中的服务提供商管理员，您可以通过 NetApp 服务引擎 Web UI 执行配置，报告，计费和管理拥有自己订阅的客户的功能。您可以执行以下功能：

* 查看在其 Flex 订阅服务中订阅和配置的存储。
+

NOTE: 作为一项服务，您可以向客户销售比从 NetApp 购买更多的容量（超额预订）。租户订阅可以延长到当前 Flex 订阅期限之后，但在创建订阅时以及信息板 / 报告中会显示警告。

* 创建，查看，修改和删除分区，区域， 租户，子租户和用户。
* 在 Flex 订阅服务中管理和托管多个租户：创建和管理租户订阅，以及查看您自己的 Flex 订阅详细信息。
+

NOTE: 可以根据相应的分区和 Keystone Flex 订阅创建租户订阅。它们是根据您的 Flex 订阅的订阅容量下提供的服务级别创建的。

* 创建文件服务器或块存储并初始化块，文件和对象存储，因为您知道为租户配置每种存储类型的网络要求。
* 您还可以为租户创建和管理子网，
* 查看在 Flex 订阅中创建的文件共享，磁盘和分段。此外，还可以创建和管理对象存储组和用户。
* 根据您的 NetApp Keystone 灵活订阅，租户订阅以及所有租户的使用情况创建报告，以便在相应的计费和评级系统中使用。
* 查看所有租户和客户以及仅订阅或配置的存储的计费和报告。
* 在您自己的（合作伙伴 / 服务提供商的）服务请求工具（与 OpsRamp / GSSC 集成）中查看和管理客户提出的服务请求。




== 您可以作为客户 / 租户管理员执行的活动

作为租户管理员，您可以有权查看自己租户的订阅详细信息并为子租户执行管理任务。您可以执行以下操作：

* 查看租户订阅服务中订阅和配置的存储。
* 在租户订阅服务中管理和托管多个子租户和用户。
* 查看分区，区域，租户和子网。
* 查看文件服务器并创建文件共享，磁盘和存储分段。
* 为租户和子租户创建报告，以便仅查看为租户和子租户订阅或配置的存储的使用数据。
* 在服务提供商的服务请求工具中提出和更新服务请求。
+

NOTE: 对于其他订阅，您可以使用服务请求工具。


