---
sidebar: sidebar 
permalink: sewebiug_define_network_configurations.html 
keywords: netapp, keystone, subnet, subtenant, network, tenant network, IPspace, VLAN, port 
summary: 创建和删除子网 
---
= 定义租户和子租户的网络配置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
服务提供商或合作伙伴管理员可以根据租户的订阅区域为租户定义网络配置，并为每个网络配置分配 VLAN 。他们还可以创建一个子网，其中每个 VLAN 都属于同一个分区和租户，并将其分配给该租户下的子租户。

创建子网需要预先配置租户网络。当子租户或最终客户配置文件服务器或块存储时，需要子网。文件和块存储 VM 属于 NetApp 服务引擎中的子租户，而它们属于 ONTAP 中的 IP 空间。在子租户级别定义网络边界时， NetApp 服务引擎中的子租户将映射到该区域的单个 ONTAP IP 空间。这样可以消除风险，并确保两个不同的子租户不会选择相同的 VLAN ID ，而最终会位于同一 IP 空间中。

* 每个分区可以创建多个子网。对于租户下的每个分区，都有一个分配的 VLAN 列表。对于所有这些可用的 VLAN ，可以创建相应的子网。子网和 VLAN 之间存在 1 ： 1 映射。而一个是子网和分区之间的多个映射。
* 一个租户可以有多个子网，一个区域下的每个可用 VLAN 可以有一个子网。它们会显示在每个分区的单个网络配置下。
* 每个网络子网只能有一个 VLAN 。每个网络配置都会显示可用 VLAN 的列表。
* 对于子租户，只能为一个分区和 VLAN 组合创建一个子网。



NOTE: 租户管理员只能查看其租户的网络配置及其子租户的子网。



== 定义租户的网络配置

作为合作伙伴管理员，您可以为每个租户创建网络配置。可以根据每个租户的需求为其分配一个可配置且唯一的 VLAN 池。删除租户后，与其关联的 VLAN 将释放回租户 VLAN 池。

.开始之前
* 确保已创建租户
* 您应了解分区、VLAN、子网CIDR和端口覆盖配置


.步骤
. 从 * 管理 * > * 租户 * 中，选择所需的租户。
. 单击网络图标。此时将显示网络屏幕，其中列出了租户的网络配置。
. 单击 * 创建网络 * 。如果适用，请指定分区， VLAN 和端口覆盖。如果定义了端口覆盖、请从下拉列表中选择已分配的端口。对于该租户的所有网络连接、将使用此端口、而不是默认端口。
+

NOTE: 端口覆盖由支持团队在区域配置期间配置。如果未指定端口覆盖、则网络将使用默认端口并为该租户创建新的VLAN。

. 单击 * 创建 * 。此时将在网络屏幕上为租户列出新的网络配置。


如果为某个分区创建了网络配置，则只能为该网络配置分配新的 VLAN 。单击 * + * 图标并添加 VLAN 和端口覆盖详细信息。单击 * 更新 * 。



== 为子租户创建子网

作为合作伙伴管理员，您可以从 * 网络 * > * 子网 * 为子租户创建子网。子网定义包括在 ONTAP 中实施的 VLAN ID ， CIDR 地址范围和路由规范。子网与租户和区域内的 VLAN 对齐。您不能为一个分区创建具有相同 VLAN 的两个子网。

.开始之前
* 租户的 VLAN 和分区配置应已完成
* 您应了解要创建的子网的要求


.步骤
. 选择所需的租户。您为其创建子网的子租户应位于此租户下。
. 单击 * 网络 * > * 子网 * 。您可以在 * 子网 * 页面上查看为子租户创建的子网列表。
. 单击 * 创建子网 * 。
. 指定子租户，分区，子网名称， VLAN 和子网 CIDR 。您还可以添加路由规范和标记。
+

NOTE: 在路由规范中， * 目标 * 应是唯一的且属于所述 VLAN ，多个路由的 * 度量 * 值可以相同。

. 单击 * 创建 * 。



NOTE: 您不能编辑或删除子网。您只能编辑与其关联的标记。
