---
sidebar: sidebar 
permalink: sewebiug_back_up_file_shares_and_disks.html 
keywords: netapp, keystone, backup, create, modify, delete, restore 
summary: 创建，修改和删除备份或从备份还原 
---
= 备份文件共享和磁盘
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以定义备份策略、以便为环境中的卷(文件共享和磁盘)创建备份、并远程维护主卷的多个副本。


NOTE: 创建或编辑卷的备份策略时、系统会自动创建备份。您不能从NetApp服务引擎界面创建备份。您可以使用备份API为卷创建和管理备份。

有关信息，请参见 link:seapiref_backups_apis.html["备份API"]

您可以通过在Flex订阅中启用的NetApp SnapMirror技术来备份源卷。有关信息，请参见 link:index.html#flex-subscription["此处"]。

创建或编辑卷时、您可以定义其备份计划。备份按预期间隔进行、并存储在目标系统上。要使备份正常运行、应与目标环境建立SnapMirror关系。从不同区域复制的文件共享和磁盘存储在每个集群上的专用备份 Storage VM （ Storage Virtual Machine ，也称为 SVM ）上。可以在不同分区中的两个独立 ONTAP 集群之间执行备份。

NetApp 服务引擎支持的标准备份策略包括：

* 临时
* 每天
* 每周
* 每月


对于在后端创建的备份、卷应处于`正常运行`状态。有关对象状态的详细信息、请参见Operational (对于备份的源对象) link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["此处"]。

如果您的卷不遵循 NetApp 服务引擎支持的标准备份策略，则可以 link:sewebiug_raise_a_service_request.html["提出服务请求"] 用于修复问题描述的 * 非标准卷 * 类别。

您可以在*备份*页面上查看为文件共享和磁盘创建的备份列表。备份将根据选定租户显示。



== 编辑备份策略或计划

创建或编辑文件共享和磁盘时、您可以定义其备份策略。备份是根据您指定的策略在后端进行的。有关信息，请参见 link:sewebiug_create_a_new_file_share.html["创建文件共享"] 或 link:sewebiug_create_a_new_disk.html["创建磁盘"]。

.步骤
. 启用 * 备份策略 * 。
. 指定备份分区以及临时，每日，每周和 / 或每月要执行的备份数。
. 单击 * 创建 * 。



NOTE: 您也可以通过编辑现有文件共享或磁盘的备份策略来计划备份。



== 修改或断开备份源

对于文件共享或磁盘的选定备份对象，您可以禁用备份或将备份对象从其源断开并使其成为孤立备份。此操作将中断与源的 SnapMirror 关系。您还可以修改临时，每日，每周和 / 或每月要创建备份的数量。

.步骤
. 在左侧导航窗格中、单击*备份*。您可以看到为环境中的所有对象创建的备份列表。
. 在列表中找到备份(按卷名称搜索)、然后单击行末尾的编辑图标。
. 根据需要更改备份源以及每种备份类型的数量。您可以通过将备份源更改为 * 无（孤立） * 来中断与源卷的 SnapMirror 关系。即使删除了源卷，这些备份也会保留为孤立备份以供还原。备份对象的状态发生变化，源卷的状态（孤立卷或已删除卷）将附加到同一列表中的源卷名称。有关对象状态的信息，请参见 link:sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["此处"]
. 单击 * 完成 * 。快照已修改。如果您已断开与源的 SnapMirror 关系，即孤立备份对象，则在 * 备份 * 选项卡中，源的名称将显示为 `d已显示` 。



NOTE: 您还可以通过在创建共享/编辑共享和创建磁盘/编辑磁盘屏幕中为卷禁用*备份策略*来中断与源卷的SnapMirror关系。



== 请求备份和还原支持

您可以 link:sewebiug_raise_a_service_request.html["提出服务请求"] 从特定恢复点还原文件共享或磁盘。

.步骤
. 从左侧导航窗格中选择 * 支持 * ，然后选择 * 服务请求 * 。
. 单击 * 新建服务请求 * 。
. 选择 * 备份还原 * 作为服务请求的类别。
. 指定其他详细信息并继续。




== 删除备份对象

删除未使用的备份卷会增加存储空间。要删除已删除源的备份卷和恢复点、应使用备份API。


NOTE: 删除备份后，备份的所有恢复点都将被删除。此外，即使删除主文件共享或磁盘，备份也会保留为孤立备份，其中包含所有恢复点以供还原。
