---
sidebar: sidebar 
permalink: sewebiug_modify_a_file_share.html 
keywords: netapp, keystone, modify, file, share, 
summary: keystone 修改文件共享 
---
= 修改文件共享
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以更改共享名称、服务级别、容量、快照策略、导出策略、 访问控制列表(ACL)和文件共享中的标记。


NOTE: 如果可用、您可以使用此方法将共享移动到不同的服务级别。只有当服务器支持相应的服务时，才能更改共享类型。

文件共享必须处于运行状态。有关了解卷状态以及为使其正常运行而要采取的步骤的信息，请参见 link:sewebiug_view_disks.html["查看磁盘"] 和 link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["对象状态"]

.步骤
. 查看 link:sewebiug_view_shares.html#view-shares["共享列表"]。
. 在列表中找到共享，然后单击该共享的编辑图标。（有关使用列表中项目的详细信息，请参见 link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["列出视图操作"]）。
. 根据需要进行任何更改；有关字段说明，请参见 link:sewebiug_create_a_new_file_share.html["创建新文件共享"]。
. 单击 * 完成 * 。此操作将创建一个作业来修改共享。


修改共享将作为异步作业运行。您可以

* 在作业列表中检查作业的状态。有关跟踪作业的信息，请参见 link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["此处"]。
* 作业完成后，在共享列表中检查共享的状态。

