---
sidebar: sidebar 
permalink: sewebiug_back_up_file_shares_and_disks.html 
keywords: netapp, keystone, backup, create, modify, delete, restore 
summary: 创建，修改和删除备份或从备份还原 
---
= 备份文件共享和磁盘
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以查看和管理环境中创建的卷（文件共享和磁盘）的快照（备份或恢复点），以便远程维护主文件共享和磁盘的多个副本。

从不同区域复制的文件共享和磁盘存储在每个集群上的专用备份 Storage VM （ Storage Virtual Machine ，也称为 SVM ）上。可以在不同分区中的两个独立 ONTAP 集群之间执行备份。NetApp 服务引擎支持的标准备份策略包括：

* 临时
* 每天
* 每周
* 每月


如果您的卷不遵循 NetApp 服务引擎支持的标准备份策略，则可以 link:https://docs.netapp.com/us-en/keystone/sewebiug_raise_a_service_request.html["提出服务请求"] 用于修复问题描述的 * 非标准卷 * 类别。


NOTE: 可以随时通过 GUI 或 API 手动执行临时（非计划）备份。

您可以在 * 备份 * 页面上查看为文件共享和磁盘创建的快照列表。备份将根据选定租户显示。



== 创建备份对象

您可以通过在时定义备份策略来为卷创建 Snapshot link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_file_share.html["创建文件共享"] 或 link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_disk.html["创建磁盘"]。

.步骤
. 启用 * 备份策略 * 。
. 指定备份分区以及临时，每日，每周和 / 或每月要执行的备份数。
. 单击 * 创建 * 。



NOTE: 您也可以通过编辑现有文件共享或磁盘的备份策略来创建或计划备份。



== 修改备份对象

对于文件共享或磁盘的选定备份对象，您可以禁用备份或将备份对象从其源断开并使其成为孤立备份。此操作将中断与源的 SnapMirror 关系。您还可以修改临时，每日，每周和 / 或每月要创建备份的数量。

.步骤
. 在列表中找到该备份，然后单击行末尾的编辑图标。
. 根据需要更改备份源以及每种备份类型的数量。您可以通过将备份源更改为 * 无（孤立） * 来中断与源卷的 SnapMirror 关系。即使删除了源卷，这些备份也会保留为孤立备份以供还原。备份对象的状态发生变化，源卷的状态（孤立卷或已删除卷）将附加到同一列表中的源卷名称。有关对象状态的信息，请参见 link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["此处"]
. 单击 * 完成 * 。已修改此 Snapshot 。如果您已断开与源的 SnapMirror 关系，即孤立备份对象，则在 * 备份 * 选项卡中，源的名称将显示为 `d已显示` 。



NOTE: 您还可以通过对源卷禁用 * 备份策略 * 来中断与源卷的 SnapMirror 关系。



== 删除备份对象

删除未使用的备份卷以增加存储空间。

.步骤
. 在列表中找到备份，然后单击行末尾该对象的删除图标。
. 在 * 确认删除 * 对话框中，输入备份名称（源卷名称）以确认要删除备份对象。
. 单击 * 确认 * 。



NOTE: 删除备份后，备份的所有恢复点都将被删除。此外，即使删除主文件共享或磁盘，备份也会保留为孤立备份，其中包含所有恢复点以供还原。要删除已删除源的备份卷和恢复点，应从 * 备份 * 选项卡中明确删除备份对象。



== 备份还原

您可以 link:https://docs.netapp.com/us-en/keystone/sewebiug_raise_a_service_request.html["提出服务请求"] 从特定恢复点还原文件共享或磁盘。

.步骤
. 从左侧导航窗格中选择 * 支持 * ，然后选择 * 服务请求 * 。
. 单击 * 新建服务请求 * 。
. 选择 * 备份还原 * 作为服务请求的类别。
. 指定其他详细信息并继续。

