---
sidebar: sidebar 
permalink: sewebiug_managing_tenants_and_subtenants.html 
keywords: netapp, keystone, managing, subtenants, 
summary: 管理子租户的 Keystone 
---
= 管理租户和子租户
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用 NetApp 服务引擎查看和管理租户和子租户。初始租户由 NetApp 支持部门为服务提供商 / 合作伙伴和租户设置。区域，分区和订阅已由支持人员配置，在您的租户下创建租户和子租户时，这些区域，分区和订阅均可用。



== Tenants

如果您是合作伙伴管理员，则可以从 * 管理 * > * 租户 * 中创建，修改和删除租户。租户管理员只能查看其各自的租户订阅和子租户。对于合作伙伴租户，您还可以定义网络。



=== 创建租户

如果您是合作伙伴管理员，则可以创建租户。您还可以为每个租户创建和管理网络。有关创建网络的详细信息，请参见 link:sewebiug_define_network_configurations.html["使用子网定义网络配置"]。

.步骤
. 单击 * 创建租户 * 。
. 添加名称和代码。表示租户的代码在 NetApp 服务引擎实例中应是唯一的，并由小写字符组成。
. 单击 * 创建 * 。



NOTE: 您只能修改现有租户的名称和问题描述。此外，您不能删除具有关联子租户或存储组件的租户。



== 子租户

如果您是合作伙伴管理员或租户管理员，则可以查看和管理子租户。



=== 创建子租户

如果您是合作伙伴管理员或租户管理员，则可以从 * 管理 * > * 子租户 * 中创建，修改和删除子租户。您还可以为每个子租户创建和管理网络。

有关创建网络的详细信息，请参见 link:sewebiug_define_network_configurations.html["使用子网定义网络配置"]。

.步骤
. 单击 * 创建子租户 * 。
. 添加名称和代码。代表子租户的代码在 NetApp 服务引擎实例中应是唯一的，并由小写字符组成。
. 单击 * 创建 * 。



NOTE: 您只能修改现有子租户的名称。此外，您不能删除与存储组件关联的子租户。
