---
sidebar: sidebar 
permalink: sewebiug_managing_subscriptions.html 
keywords: netapp, keystone, managing, subscriptions, 
summary: 管理订阅的 Keystone 
---
= 管理订阅
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
管理订阅包括为 NetApp Keystone 灵活订阅（ Flex 订阅）和租户订阅服务分配服务级别，或者使用 NetApp 服务引擎界面为服务级别分配容量并更改容量。

服务提供商 / 合作伙伴与 NetApp 之间的关系以及租户订阅所代表的 Flex 订阅代表服务提供商与其租户和子租户（最终客户）之间的关系。当 NetApp 管理员或 GSSC 为合作伙伴和租户创建 Flex 订阅服务时，这意味着存储分配已完成。但是，除非创建服务级别并完成相应的容量分配，否则子租户或最终客户将无法使用存储。合作伙伴管理员可以为其 Flex 订阅和租户订阅管理存储。租户管理员只能查看其自己租户的租户订阅详细信息和服务。



== 管理 Flex 订阅（ Keystone 订阅）

如果您是合作伙伴管理员，则可以通过 * 订阅 * > * Keystone 订阅 * 查看和管理您的 Flex 订阅服务。* Keystone 订阅 * 表示 NetApp 合作伙伴管理员创建的 Flex 订阅服务。合作伙伴管理员可以查看其 Flex 订阅服务并创建服务请求，以便：

* 增加订阅容量
* 将服务添加到订阅（分配服务级别和容量）


服务请求由支持团队接收和处理。

您还可以在单独的选项卡中查看和管理订阅的数据保护和高级保护服务。



=== 增加订阅容量

您可以增加任何已订阅服务级别的已承诺容量，以满足增长要求。

.步骤
. 从下拉菜单中选择要增加容量的订阅。
. 单击所需服务级别的 * 增加容量 * 。
. 指定所需的容量（以 TiB 为单位）。
. 单击 * 确认 * 。




=== 将服务添加到订阅

您可以将服务添加到订阅。添加服务包括为订阅分配服务级别以及为同一服务级别指定容量。

订阅可能只具有每个性能级别之一，例如，如果您的订阅已包含 Extreme 和 Standard 服务，则可以添加 Premium 或 Block 服务。

.步骤
. 从下拉菜单中选择要增加容量的订阅。
. 单击 * 添加服务 * 。
. 从下拉菜单中选择要添加的订阅服务，然后将要提交到服务级别的容量（以 TiB 为单位）添加到服务级别。
. 单击 * 确认 * 。



NOTE: 如果您订阅了极高分层或高级分层，则可以编辑任何现有订阅的性能级别，并选择启用分层的性能级别。您还可以选择从启用了分层的性能级别转变为非分层性能级别。



== 管理租户订阅

如果您是合作伙伴管理员，则可以从 * 订阅 * > * 租户订阅 * 创建，查看和更新租户订阅。如果您是租户管理员，则只能查看订阅。



=== 创建租户订阅

您可以为租户创建新订阅。

.步骤
. 单击 * 新建订阅 * 。
. 指定区域，区域，订阅期限，速率计划和其他详细信息。租户订阅将根据选定区域分配给 Keystone 订阅。这是因为每个 Keystone 订阅都绑定到一个分区。
+

NOTE: 您不能创建重叠的订阅。开始日期应至少为第二天，因为订阅将在指定开始日期的前一天开始。此外，它不能自当前日期起超过 30 天。

. 单击 * 创建 * 。


您不能删除任何订阅。您只能编辑现有租户订阅并添加新服务级别，增加服务级别的已提交容量以及为订阅添加标记。
